### ISSUE TITLE
CrossOutMathElements not working

### ISSUE THREAD

**Issue by rensx** [davidgutierrezrubio/jmathanim#17]
(1)CrossOutMathElements
(2)SVGUtils.parseStyleAttribute
	solution:str = str.replaceAll("(?<=[;:])\\s*", "");
(3)PlaySoundAt=>solution:
    FFmpegAudioEncoder.runFfmpegProcess
        String[] c={"sh","-c",cmd};

**Comment by davidgutierrezrubio** [comment]
Thank for the suggestions!
Bug in CrossOutMathElements is fixed and applied to the SNAPSHOT version as well as your suggestions.
