### ISSUE TITLE
"WARN - no style with name DOTDEFAULT found"

### ISSUE THREAD

**Issue by eadem-mutata-resurgo** [davidgutierrezrubio/jmathanim#8]
I'm going through the user manual and when running the second demo program (the one with the moving dot which creates an MP4 file) I get this error repeating in the terminal in VScode. The program runs but the point object doesn't show up in the animation, it's just a black screen:

"WARN  - No style with name DOTDEFAULT found"

I'm very new at this so it's most likely an issue with my setup (maven, JDK, etc.) rather than your code but I have no idea how to troubleshoot this issue- google isn't giving me any relevant results.

**Comment by davidgutierrezrubio** [comment]
Hi Eadem. It seems the DOTDEFAULT style is not properly loaded when no style template is loaded. For now the solution is simply to add the line config.parseFile("#dark.xml") in the setupSketch() method for example. User manuas has been updated to include this line.

I will correct this in the next snapshot version. Thank you!!
