### ISSUE TITLE
Two files' name collide in Windows OS. 

### ISSUE THREAD

**Issue by henryscala** [davidgutierrezrubio/jmathanim#9]
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/main/java/com/jmathanim/Constructible/Conics/CTCIrcleSector.java'
  'src/main/java/com/jmathanim/Constructible/Conics/CTCircleSector.java'

**Comment by davidgutierrezrubio** [comment]
Deleted file CTCIrcleSector.java from source tree. Thank you.
